[package]
name = "microblog-rpc"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
prost = "0.13.4"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
tonic = "0.12.3"
tonic-build = "0.12.3"

[build-dependencies]
tonic-build = "0.12.3"
